name: NPM install dependencies + GHCR Build and Push

on:
  workflow_call:
    inputs:
      node-version:
        required: true
        type: string
      ghcr-image-name:
        required: true
        type: string
      ghcr-owner:
        required: true
        type: string

jobs:
  checkout:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ inputs.node-version }}

      - name: Install NPM dependencies
        run: npm install

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ inputs.ghcr-owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ inputs.ghcr-owner }}/${{ inputs.ghcr-image-name }}:${{ github.sha }}
            ghcr.io/${{ inputs.ghcr-owner }}/${{ inputs.ghcr-image-name }}:latest
