name: NPM install dependencies + Docker Hub Build and Push

on:
  workflow_call:
    inputs:
      docker-hub-image-name:
        required: true
        type: string
      docker-hub-owner:
        required: true
        type: string
    secrets:
      DOCKERHUB_TOKEN:
        required: true

jobs:
  build-push-docker-hub:
    timeout-minutes: 30
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ inputs.docker-hub-owner }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: |
            ${{ inputs.docker-hub-owner }}/${{ inputs.docker-hub-image-name }}:${{ github.sha }}
            ${{ inputs.docker-hub-owner }}/${{ inputs.docker-hub-image-name }}:latest
