name: GHCR Build and Push

on:
  workflow_call:
    inputs:
      ghcr-image-name:
        required: true
        type: string
      ghcr-owner:
        required: true
        type: string
      additional-tags:
        required: false
        type: string

jobs:
  build-push-ghcr:
    timeout-minutes: 30
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ inputs.ghcr-owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          #sbom: true | not tested
          tags: |
            ghcr.io/${{ inputs.ghcr-owner }}/${{ inputs.ghcr-image-name }}:${{ github.sha }}
            ghcr.io/${{ inputs.ghcr-owner }}/${{ inputs.ghcr-image-name }}:latest
            ${{ inputs.additional-tags }}