name: Super-Linter Static Frontend

on:
  workflow_call:
    inputs:
      VALIDATE_CSS:
        type: boolean
        required: false
        default: true
      VALIDATE_HTML:
        type: boolean
        required: false
        default: true

jobs:
  linit-code:
    timeout-minutes: 15
    name: Static front lint
    runs-on: ubuntu-latest
    permissions:
      contents: read
      statuses: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Lint Code Base
        uses: github/super-linter@v4
        env:
          GITHUB_TOKEN: ${{ github.token }}
          VALIDATE_ALL_CODEBASE: true
          DEFAULT_BRANCH: main
          VALIDATE_CSS: ${{ inputs.VALIDATE_CSS }}
          VALIDATE_HTML: ${{ inputs.VALIDATE_HTML }}
