name: Lint Code Base

on:
  workflow_call:
    inputs:
      VALIDATE_JAVASCRIPT_ES:
        type: boolean
        required: false
        default: true
      VALIDATE_TYPESCRIPT_ES:
        type: boolean
        required: false
        default: true
      VALIDATE_CSS:
        type: boolean
        required: false
        default: true
      VALIDATE_HTML:
        type: boolean
        required: false
        default: true
    secrets:
          GITHUB_TOKEN:
            required: false

jobs:
  build:
    name: Lint Code Base
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Lint Code Base
        uses: github/super-linter@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN || github.token }}
          VALIDATE_ALL_CODEBASE: true
          DEFAULT_BRANCH: main
          VALIDATE_JAVASCRIPT_ES: ${{ inputs.VALIDATE_JAVASCRIPT_ES }}
          VALIDATE_TYPESCRIPT_ES: ${{ inputs.VALIDATE_TYPESCRIPT_ES }}
          VALIDATE_CSS: ${{ inputs.VALIDATE_CSS }}
          VALIDATE_HTML: ${{ inputs.VALIDATE_HTML }}
