name: Patch Versioning on Push

on:
  workflow_call:
    outputs:
      version:
        description: 'The new version'
        value: ${{ jobs.versioning.outputs.new_version }}

jobs:
  versioning:
    runs-on: ubuntu-latest
    outputs:
      new_version: ${{ steps.versioning.outputs.version }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get and Increment Version
        id: versioning
        run: |
            # If the file VERSION doesnt exists, create it
            if [ ! -f VERSION ]; then
              echo "0.1.0" > VERSION
            fi

            # Read current version
            current_version=$(cat VERSION)
            echo "Current version: $current_version"

            # Split major, minor, patch
            IFS='.' read -r major minor patch <<< "$current_version"
            
            # Increment patch
            new_patch=$((patch + 1))
            new_version="$major.$minor.$new_patch"
            echo "New version: $new_version"

            # Save new version on VERSION
            echo $new_version > VERSION

            # Export the new version as output to be used in another workflow with docker tag
            echo "version=$new_version" >> $GITHUB_OUTPUT
            
      - name: Commit and push updated version
        run: |
          git config --local user.name "GitHub Actions"
          git config --local user.email "actions@github.com"
          git add VERSION
          git commit -m "Increment version to ${{ steps.versioning.outputs.version }}"
          git push
